# Generated by Django 2.2.2 on 2019-06-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='conatact_date',
            new_name='contact_date',
        ),
    ]
